name: Build documentation

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  
          
      - name: Check for Build Flag
        id: check-flag
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "TRIGGER_BUILD=false" >> $GITHUB_ENV
          if [[ "${{ github.event.head_commit.message }}" =~ \[build-docs\] ]]; then
            echo "TRIGGER_BUILD=true" >> $GITHUB_ENV
          fi
          
      - name: Install dependencies
        if: env.TRIGGER_BUILD == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install pymdown-extensions
          pip install mkdocstrings
          pip install mkdocstrings-python
          pip install -e .
          
      - name: Build MkDocs site
        if: env.TRIGGER_BUILD == 'true'
        run: mkdocs build
        
      - name: Build and deploy to GitHub Pages
        if: env.TRIGGER_BUILD == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_branch: gh-pages  
          publish_dir: ./site  
