name: Build documentation

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install pymdown-extensions
          pip install mkdocstrings
          pip install mkdocstrings-python
          pip install -e .
          
      - name: Check for Build Flag
        id: check-flag
        run: |
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          if [[ "${{ github.event.head_commit.message }}" == *"[build-docs]"* ]]; then
            echo "::set-output name=trigger::true"
          fi

      - name: Build MkDocs site
        if: steps.check-flag.outputs.trigger == 'true'
        run: mkdocs build

      - name: Build and deploy to GitHub Pages
        if: steps.check-flag.outputs.trigger == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_branch: gh-pages  
          publish_dir: ./site  
